server:
  port: 8080
  
eureka:  client:    enabled: false
   
ribbon:  eureka:    enabled: false
 
spring:
  application:
    name: api-gateway  
  cloud:
    gateway:     
      routes:
      - id: microservice-users
        uri: "${proxy.users}"
        predicates:
        - Path=/user/**

      - id: microservice-gps
        uri: "${proxy.gps}"
        predicates:
        - Path=/gps/**

      - id: microservice-rewards
        uri: "${proxy.rewards}"
        predicates:
        - Path=/rewards/**

  
         
logging:
  level:
     '[com.tourGuide.apiGateway]': DEBUG
   